server:
    listener:
        ipv4: 127.0.0.1
        port: 80
    log_path: '/var/log/www/general.log'
    methods: 
        - POST
        - HEAD
        - PUT
        - DELETE
        - GET
        - OPTIONS
    name: localhost
    threading: false
    thread_count: 8
    user: wwe-data
    webroot: '/var/www/html'

defaults:
    default_index: index.html
    error_pages:
        403: docs/403.html
        404: docs/404.html
        405: docs/405.html
        500: docs/500.html
    file_ext:
        - html
        - htm
        - png
        - txt
        - jpeg
        - jpg
        - gif
        - css
    secondary_index: index.htm
